#this file is used instead of .profile when zsh is the login shell
#.zprofile located in ZDOTDIR is used instead of others
export ZDOTDIR="$HOME/.dotfilerepo/shell/zsh"

#display android studio
export _JAVA_AWT_WM_NONREPARENTING=1
